#!/usr/bin/env python

import urllib2
import json
import sys

def create_version_properties(optimus,type,arch,product=None):
    if product:
        page = urllib2.urlopen('http://{0}:9090/query_enterprise?deliverable_type={1}&os_architecture={2}&product={3}'.format(optimus,type,arch,product))
    else:
        page = urllib2.urlopen('http://{0}:9090/query_enterprise?deliverable_type={1}&os_architecture={2}'.format(optimus,type,arch))
    arr = json.loads(page.read())
    if arr:
        dict = arr[0]
        properties = open('version.properties', 'w')
        line1 = 'url={0}'.format(dict['url'])
        line2 = 'version_number={0}'.format(dict['product_version'])
        properties.writelines([line1,'\n',line2,'\n'])
        properties.close()
    page.close()


if __name__ == "__main__":
    print sys.argv
    optimus = sys.argv[1]
    type = sys.argv[2]
    arch = sys.argv[3]
    if len(sys.argv) == 5:
       product = sys.argv[4]
       create_version_properties(optimus,type,arch,product)
    else:
       create_version_properties(optimus,type,arch)
